/**
 * Hand-transformed copy of apps/web/src/data/courses.ts's COURSES -- not a
 * live cross-app import, keeps the workspace boundary clean. Prices were
 * already USD cents in the frontend source, so they map 1:1 to
 * priceUsdCents. All ten courses ship with curriculum: [] today; modules
 * and lessons tables exist and are RLS'd, but no course has real curriculum
 * content yet, so every course here seeds zero modules.
 */
export interface CourseSeed {
  slug: string;
  title: string;
  categoryKey: string;
  domainSlug: string | null;
  summary: string;
  description: string;
  priceUsdCents: number | null;
  priceWasUsdCents: number | null;
  pricing: 'paid' | 'free' | 'subscription';
  level: 'beginner' | 'intermediate' | 'advanced' | 'all_levels';
  durationHours: number;
  durationLabel: string;
  rating: number;
  ratingCount: number;
  enrolledCount: number;
  badges: ('featured' | 'new_badge' | 'hot' | 'special' | 'coming_soon')[];
  instructorId: string | null;
  image: string;
  outcomes: string[];
  requirements: string[];
  audience: string[];
  toolsCovered: string[];
  certification: string;
  status: 'draft' | 'published';
  publishedAt: string | null;
}

export const COURSES: CourseSeed[] = [
  {
    slug: 'ai-engineering-associate-ai-engineer',
    title: 'AI Engineering / Associate AI Engineer',
    categoryKey: 'cat-ai',
    domainSlug: 'artificial-intelligence',
    summary:
      'A comprehensive foundation in Artificial Intelligence Engineering, machine learning, deep learning, NLP, computer vision, Generative AI, MLOps and AI deployment.',
    description:
      'This course introduces participants to the end-to-end AI engineering lifecycle, from data preparation and model development to deployment and monitoring. Learners will explore machine learning, deep learning, large language models, AI infrastructure, and modern AI engineering practices used in industry. Artificial Intelligence Engineering combines software engineering, machine learning, data science, and cloud technologies to build intelligent systems that solve real-world problems.',
    priceUsdCents: 18000,
    priceWasUsdCents: 20000,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 120,
    durationLabel: '3 Months (120 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 76,
    badges: ['special', 'featured'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/ai-engineering.jpg',
    outcomes: [
      'Understand Artificial Intelligence concepts and workflows',
      'Develop machine learning models for predictive analytics',
      'Build deep learning applications using neural networks',
      'Implement Natural Language Processing (NLP) solutions',
      'Develop Computer Vision applications',
      'Build AI-powered chatbots and assistants',
      'Deploy AI applications to cloud platforms',
      'Apply MLOps principles for AI lifecycle management',
      'Integrate Large Language Models into applications',
      'Build production-ready AI solutions',
    ],
    requirements: [
      'Basic computer literacy',
      'Familiarity with programming concepts',
      'Basic Python knowledge is recommended',
      'Understanding of mathematics is beneficial but not mandatory',
      'Access to a computer with internet connectivity',
    ],
    audience: [
      'Aspiring AI Engineers',
      'Software Developers',
      'Data Scientists and Analysts',
      'Machine Learning Enthusiasts',
      'Computer Science Students',
      'IT Professionals seeking AI specialization',
      'Technology Entrepreneurs',
      'Researchers interested in Applied AI',
    ],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'generative-ai-and-large-language-models-llms',
    title: 'Generative AI and Large Language Models (LLMs)',
    categoryKey: 'cat-ai',
    domainSlug: 'artificial-intelligence',
    summary:
      'How modern AI systems such as ChatGPT and other foundation models work, transformer architectures, prompt engineering and building AI-powered applications.',
    description:
      'This course explores Generative AI technologies and Large Language Models (LLMs), focusing on how AI generates text, code, images, and other digital content. Participants will learn the principles behind foundation models, prompt engineering, AI application development, model deployment, and ethical AI practices.',
    priceUsdCents: 14000,
    priceWasUsdCents: null,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 40,
    durationLabel: '1 Month (40 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 66,
    badges: ['hot'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/generative-ai-and-large-language-models-llms.jpg',
    outcomes: [
      'Understand Generative AI concepts and applications',
      'Explain how Large Language Models (LLMs) work',
      'Apply effective prompt engineering techniques',
      'Build AI-powered applications using APIs and frameworks',
      'Generate and analyze text, code, and multimedia content',
      'Fine-tune and customize AI models',
      'Integrate AI into business and software workflows',
      'Apply ethical and responsible AI practices',
    ],
    requirements: [
      'Basic computer literacy',
      'Familiarity with internet technologies',
      'Interest in Artificial Intelligence and Machine Learning',
      'Basic programming knowledge is beneficial but not mandatory',
      'Access to a computer with internet connectivity',
    ],
    audience: [
      'AI Enthusiasts',
      'Software Developers',
      'Data Scientists',
      'Machine Learning Engineers',
      'Business Professionals seeking AI skills',
      'Digital Content Creators',
      'Researchers and Students interested in Artificial Intelligence',
      'Technology Entrepreneurs',
    ],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'data-science-and-analytics',
    title: 'Data Science & Analytics',
    categoryKey: 'cat-data',
    domainSlug: 'data-analytics-data-science',
    summary:
      'Collect, process, analyze and visualize data to uncover insights and support business decision-making, data analysis, business intelligence, statistics and predictive modelling.',
    description:
      'This course explores the complete data science lifecycle, from data acquisition and preparation to analysis, visualization, and predictive analytics. Participants will learn how organizations use data to solve business problems, improve operations, and gain competitive advantages.',
    priceUsdCents: 18000,
    priceWasUsdCents: 25000,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 80,
    durationLabel: '2 Months (80 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 60,
    badges: ['special'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/data-sci-and-analytics.jpg',
    outcomes: [
      'Understand the fundamentals of Data Science and Analytics',
      'Collect, clean, and prepare datasets for analysis',
      'Perform exploratory data analysis (EDA)',
      'Apply statistical techniques to solve business problems',
      'Create compelling data visualizations and dashboards',
      'Use Python and analytical tools for data analysis',
      'Build predictive models using machine learning techniques',
      'Communicate insights through reports and presentations',
    ],
    requirements: [
      'Basic computer literacy',
      'Familiarity with Microsoft Excel or spreadsheets',
      'Basic mathematical understanding',
      'Interest in data analysis and problem-solving',
      'Access to a computer with internet connectivity',
    ],
    audience: [
      'Aspiring Data Scientists',
      'Data Analysts',
      'Business Analysts',
      'Software Developers',
      'AI and Machine Learning Enthusiasts',
      'Researchers and Academics',
      'Entrepreneurs and Decision Makers',
      'Students pursuing technology careers',
    ],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'cloud-computing-fundamentals',
    title: 'Cloud Computing Fundamentals',
    categoryKey: 'cat-cloud',
    domainSlug: 'cloud-computing',
    summary:
      'How cloud infrastructure works and how businesses use cloud platforms to build, manage and scale applications, IaaS, PaaS and SaaS service models.',
    description:
      'Cloud Computing is the delivery of computing services such as servers, storage, databases, networking, and software over the internet. This course introduces students to the core concepts of cloud technology and how businesses use cloud platforms to build, manage, and scale applications efficiently. Learners will explore popular cloud service models such as Infrastructure as a Service (IaaS), Platform as a Service (PaaS) and Software as a Service (SaaS).',
    priceUsdCents: 14000,
    priceWasUsdCents: null,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 0,
    durationLabel: '4 Months',
    rating: 4,
    ratingCount: 6,
    enrolledCount: 295,
    badges: ['featured'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/cloud-computing-fundamentals.jpg',
    outcomes: [
      'Understand how cloud infrastructure works',
      'Explain the IaaS, PaaS and SaaS service models',
      'Deploy and manage cloud resources',
      'Reason about scaling applications on cloud platforms',
      'Understand cloud security and cost fundamentals',
    ],
    requirements: ['Basic computer literacy', 'Access to a computer with internet connectivity'],
    audience: ['Beginners in cloud computing', 'IT professionals', 'Students pursuing technology careers'],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-17',
  },
  {
    slug: 'edge-computing',
    title: 'Edge Computing',
    categoryKey: 'cat-edge',
    domainSlug: 'edge-computing',
    summary:
      'Edge computing technologies that enable data processing closer to the source of data generation, how edge supports IoT, AI, real-time analytics and next-generation digital services.',
    description:
      'This course explores Edge Computing technologies that enable data processing closer to the source of data generation. Participants will learn how Edge Computing supports IoT, AI, real-time analytics, and next-generation digital services.',
    priceUsdCents: 20000,
    priceWasUsdCents: null,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 40,
    durationLabel: '1 Month (40 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 65,
    badges: ['featured'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/edge-server-computing.jpg',
    outcomes: [
      'Understand edge computing architecture',
      'Differentiate cloud, fog, and edge computing',
      'Design edge-enabled solutions',
      'Deploy IoT applications at the edge',
      'Implement edge analytics',
      'Explore Industry 4.0 applications',
    ],
    requirements: ['Basic computer literacy', 'Access to a computer with internet connectivity'],
    audience: ['Aspiring edge and IoT engineers', 'Software and cloud engineers', 'Students pursuing technology careers'],
    toolsCovered: ['Raspberry Pi', 'EdgeX Foundry', 'AWS IoT Core', 'Azure IoT Hub', 'Node-RED', 'MQTT'],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'quantum-computing-fundamentals',
    title: 'Quantum Computing Fundamentals',
    categoryKey: 'cat-quantum',
    domainSlug: 'quantum-computing',
    summary:
      'An introduction to the revolutionary field of Quantum Computing, quantum mechanics concepts, quantum algorithms and quantum programming.',
    description:
      'This course introduces learners to the revolutionary field of Quantum Computing. Participants will explore quantum mechanics concepts, quantum algorithms, quantum programming and the future applications of quantum technologies.',
    priceUsdCents: 16900,
    priceWasUsdCents: 20000,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 40,
    durationLabel: '1 Month (40 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 57,
    badges: ['hot'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/quantum-computing-fundamentals.jpg',
    outcomes: [
      'Understand quantum computing principles',
      'Differentiate classical and quantum computing',
      'Work with quantum circuits',
      'Develop basic quantum programs',
      'Explore quantum algorithms',
      'Understand future applications of quantum technologies',
    ],
    requirements: ['Basic computer literacy', 'Interest in physics and mathematics', 'Access to a computer with internet connectivity'],
    audience: ['Students and researchers', 'Software engineers', 'Technology enthusiasts curious about quantum computing'],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'cisco-ccna-cisco-certified-network-associate',
    title: 'Cisco CCNA (Cisco Certified Network Associate)',
    categoryKey: 'cat-security',
    domainSlug: 'networking-cybersecurity',
    summary:
      'Master the fundamentals of networking and earn the globally recognized Cisco CCNA certification. Ideal for beginners, IT professionals, and students preparing for the 200-301 exam.',
    description:
      'This comprehensive CCNA course covers all official Cisco 200-301 exam topics including Network Fundamentals, Network Access, IP Connectivity, IP Services, Security Fundamentals, and Automation & Programmability. By the end of this program, students will be able to configure, manage, and troubleshoot Cisco networks.',
    priceUsdCents: 14000,
    priceWasUsdCents: null,
    pricing: 'paid',
    level: 'beginner',
    durationHours: 0,
    durationLabel: '30–45 Days (1–2 Hours per Day)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 76,
    badges: ['featured', 'special'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/cisco-ccna-cisco-certified-network-associate.jpg',
    outcomes: [
      'Configure, manage and troubleshoot Cisco networks',
      'Master Network Fundamentals and Network Access',
      'Work with IP Connectivity and IP Services',
      'Apply Security Fundamentals',
      'Understand Automation & Programmability',
      'Prepare for the official Cisco 200-301 exam',
    ],
    requirements: ['Basic computer literacy'],
    audience: ['Students', 'Aspiring network engineers', 'IT support staff'],
    toolsCovered: [],
    certification:
      'To earn the Cisco Certificate in Network Engineering & CCNA Preparation, students must complete all modules, complete all practical labs, pass the final assessment (70%+), and complete the capstone networking project. Cisco Certification · PC or Mobile.',
    status: 'published',
    publishedAt: '2026-06-16',
  },
  {
    slug: 'ethical-hacking-and-cyber-security',
    title: 'Ethical Hacking & Cyber Security',
    categoryKey: 'cat-security',
    domainSlug: 'networking-cybersecurity',
    summary:
      'A hands-on introduction to ethical hacking and cyber security, understand how attacks work so you can defend against them.',
    description:
      'This course introduces the practice of ethical hacking and cyber security: reconnaissance, scanning, exploitation and reporting in a controlled lab, and the defensive practices that harden systems against the same techniques.',
    priceUsdCents: 12800,
    priceWasUsdCents: 14000,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 40,
    durationLabel: '1 Month (40 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 49,
    badges: ['hot'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/ethical-hacking-cyber-security-by-aiit-network.jpg',
    outcomes: [
      'Understand core cyber security concepts',
      'Perform reconnaissance and vulnerability scanning',
      'Practise exploitation techniques in a controlled lab',
      'Write clear, actionable assessment reports',
      'Harden systems against common attacks',
    ],
    requirements: ['Basic computer literacy', 'Familiarity with networking is an advantage', 'Access to a computer with internet connectivity'],
    audience: ['Aspiring security analysts', 'IT professionals', 'Students pursuing technology careers'],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-17',
  },
  {
    slug: 'blockchain-technology',
    title: 'Blockchain Technology',
    categoryKey: 'cat-blockchain',
    domainSlug: 'blockchain-technology',
    summary:
      'A comprehensive introduction to Blockchain Technology and its real-world applications, architecture, consensus mechanisms, smart contracts, DeFi, NFTs and enterprise blockchain.',
    description:
      'This course explores Blockchain Technology as a secure and decentralized system for recording, validating, and managing digital transactions. Participants will learn the principles behind blockchain networks, smart contracts, decentralized applications, and emerging Web3 ecosystems.',
    priceUsdCents: 12000,
    priceWasUsdCents: 16000,
    pricing: 'paid',
    level: 'intermediate',
    durationHours: 40,
    durationLabel: '1 Month (40 Hours)',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 70,
    badges: ['featured'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/blockchain-technology.jpg',
    outcomes: [
      'Understand blockchain architecture and how blockchain networks work',
      'Explain consensus mechanisms',
      'Work with smart contracts and decentralized applications',
      'Understand cryptocurrencies, DeFi and NFTs',
      'Explore enterprise blockchain solutions and Web3 ecosystems',
    ],
    requirements: [
      'Basic computer literacy',
      'Familiarity with internet technologies',
      'Understanding of databases is beneficial',
      'Basic programming knowledge is an advantage but not mandatory',
      'Access to a computer with internet connectivity',
    ],
    audience: [
      'Aspiring Blockchain Developers',
      'Software Engineers and IT Professionals',
      'FinTech Enthusiasts',
      'Cybersecurity Professionals',
      'Business Analysts and Entrepreneurs',
      'Students interested in Web3 Technologies',
      'Digital Innovation Professionals',
    ],
    toolsCovered: [],
    certification: 'Certificate included · Certified by AIIT · PC or Mobile',
    status: 'published',
    publishedAt: '2026-06-19',
  },
  {
    slug: 'digital-and-tech-literacy-absolute-beginner',
    title: 'Digital & Tech Literacy (Absolute Beginner)',
    categoryKey: 'cat-literacy',
    domainSlug: 'digital-tech-literacy',
    summary:
      "AIIT's entry-point free course, designed for students who are new to computers, the internet, cloud computing, or artificial intelligence.",
    description:
      'Digital & Tech Literacy is AIIT’s entry-point free course, designed for students who are new to computers, the internet, cloud computing, or artificial intelligence. It builds the confidence and foundational understanding needed before starting any AIIT paid track.',
    priceUsdCents: null,
    priceWasUsdCents: null,
    pricing: 'free',
    level: 'beginner',
    durationHours: 0,
    durationLabel: '3 lectures',
    rating: 0,
    ratingCount: 0,
    enrolledCount: 50,
    badges: ['special'],
    instructorId: 'ins-aiit',
    image: '/assets/courses/aiit-student-class.webp',
    outcomes: [
      'Identify and explain the core parts of a computer and how they work together',
      'Navigate the internet safely and confidently, including basic browser and email use',
      'Explain what cloud computing is and identify examples of it in everyday life',
      'Describe the difference between traditional storage and cloud storage',
      'Define artificial intelligence in plain language and give real-world examples',
      'Recognize where AI already shows up in tools they use every day',
    ],
    requirements: ['No prior experience required'],
    audience: [
      'First-time computer or smartphone users',
      'Students preparing to enter any AIIT paid track',
      'Job seekers who need basic digital skills for employment',
      'Adult learners returning to education after time away from tech',
    ],
    toolsCovered: [],
    certification: 'Certificate included',
    status: 'published',
    publishedAt: '2026-07-07',
  },
];
