-- CONFIRMED IN PRODUCTION: this statement itself cannot run there --
-- ALTERing auth.users fails with "must be owner of table users" (42501)
-- even from the Supabase Dashboard's SQL Editor. That's a platform-level
-- protection on GoTrue's own schema, not a connection-role scoping issue
-- like the CREATE TRIGGER/SELECT cases elsewhere in this migration
-- history (see 20260912000001_auth_trigger) -- there is no elevated
-- connection on a Supabase project that can restructure auth.users by
-- hand. If this migration ever shows as failed against production again
-- (e.g. after a database reset), the only fix is
-- `prisma migrate resolve --applied 20260913015000_auth_users_meta_column`
-- with NO attempt to actually run the SQL below first -- confirm via
-- `select column_name from information_schema.columns where
-- table_schema='auth' and table_name='users'` that raw_user_meta_data is
-- already there (it always has been, on every real Supabase project)
-- before resolving.
--
-- A genuine no-op against real Supabase, which has always had this column
-- (IF NOT EXISTS). Exists purely so CI's from-scratch migration replay --
-- which starts from a minimal stub auth.users (see
-- 20260910235959_stub_auth_schema) rather than a real Supabase schema --
-- has the column in place before 20260913020000_backfill_profile_names
-- reads it. Deliberately timestamped to run before that migration despite
-- being added after it was already applied to production: confirmed
-- against a real Postgres that `prisma migrate deploy` applies a new,
-- not-yet-recorded migration regardless of where its timestamp sorts
-- relative to already-applied ones -- it does not require new migrations
-- to sort after the latest applied one.
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS raw_user_meta_data JSONB;
